ALTER TABLE game_sessions DROP CONSTRAINT game_sessions_cash_check;
ALTER TABLE game_sessions DROP CONSTRAINT game_sessions_morale_check;
ALTER TABLE game_sessions DROP CONSTRAINT game_sessions_hype_check;